### ISSUE TITLE
About the training resource

### ISSUE THREAD

**Issue by cskkxjk** [wbhu/Tri-MipRF#14]
Hi~ Thanks for your great work!
I wonder what kind of GPUs are required to train with the provided config ```config_files/ms_blender/TriMipRF.gin ```?
I failed on 1080 due to some memory issues.

**Comment by wbhu** [comment]
We tested it on A100-80g, but it only consumes about 9GB gpu memeory. If it still exceeds your gpu memory, please consider tune down Trainer.target_sample_batch_size

**Comment by cskkxjk** [comment]
> We tested it on A100-80g, but it only consumes about 9GB gpu memeory. If it still exceeds your gpu memory, please consider tune down Trainer.target_sample_batch_size

Thank you for the reply!

**Comment by Flyingdog-Huang** [comment]
> We tested it on A100-80g, but it only consumes about 9GB gpu memeory. If it still exceeds your gpu memory, please consider tune down Trainer.target_sample_batch_size

hi，I try to change the value of  Trainer.target_sample_batch_size, change to large or small from 262144, but the GPU memory did not change, which parameter can control GPU-men? 
thanks a lot!
