### ISSUE TITLE
Negative in level?

### ISSUE THREAD

**Issue by StarsTesla** [wbhu/Tri-MipRF#18]
Hi， I tried to print the level that has add log2planesize， and I found negative level shows in them which should not be happend though the model still can works

![image](https://github.com/wbhu/Tri-MipRF/assets/45264423/b888a05d-acba-4907-b012-52e65e1adce4)
![image](https://github.com/wbhu/Tri-MipRF/assets/45264423/ad409590-b33c-4855-b677-905454cb8167)

**Comment by wbhu** [comment]
The 'negative' level means the resolution of the required level is larger than the base level, which is 512 in our hyper-parameters. But for compactness consideration, we still set 512 as the base resolution, the negative values will be clipped into zeros during the feature querying.

**Comment by StarsTesla** [comment]
@wbhu 另一个问题就是，如果我设置比如说1024，那是不是负值会更少一些

**Comment by SYSUykLin** [comment]
I think the negative level occured is because the bbox is too large. $level = log(r) - log(r_{bbox}) + log2(resolution)$。Other projects(instantNGP, Triplane) set the bbox 0.5 or 1

**Comment by StarsTesla** [comment]
@SYSUykLin I thought this too, while I recall that I tried before in this code, like aabb in -1.0 to 1.0, I get a kindof not good optimizing process( converge slow at first compare to 1.5).

**Comment by SYSUykLin** [comment]
> @SYSUykLin I thought this too, while I recall that I tried before in this code, like aabb in -1.0 to 1.0, I get a kindof not good optimizing process( converge slow at first compare to 1.5).

The same as u. I add the TriMipRF into pytorch-lightning and use nerfacc==0.5.3, 在lego上只是速度慢了，结果还是差不多，但是ship数据集上就完全不同，scale=0.5（这是ngp-pl在合成数据集上的参数）只能跑到25左右，scale=1.5才能达到paper结果。似乎这个scale很重要

**Comment by SYSUykLin** [comment]
> @SYSUykLin I thought this too, while I recall that I tried before in this code, like aabb in -1.0 to 1.0, I get a kindof not good optimizing process( converge slow at first compare to 1.5).

On lego, the speed is just slower, and the results are still similar, but on the ship data set, it is completely different. Scale=0.5 (this is the parameter of ngp-pl on the synthetic data set) can only run to about 25, and scale=1.5 can achieve it. paper results. It seems that this scale is very important

**Comment by Terry10086** [comment]
请教一下，我在测试chair数据集的时候，level都是负数，如果这样的话，那对应的mipmap不就变成全都是1种类型的平面了吗？那这种情况下，相当于内切球的半径大小并不会对结果产生影响，那trimiprf还是多尺度的表达吗？

When I evaluate the chair dataset, the levels are all negative. If so, wouldn't the corresponding mipmap become all one type of plane? In this case, the size of the radius equivalent to the inscribed sphere does not affect the results. Is trimiprf still a multi-scale expression?
