### ISSUE TITLE
Difference between Zip-NeRF and Tri-MipRF?

### ISSUE THREAD

**Issue by YJ-142150** [wbhu/Tri-MipRF#2]
Great Work!!!
Could you explain more about "Zip-NeRF introduces a multi-sampling-based method to address the same problem, efficient anti-aliasing, while our method belongs to the pre-filtering-based method."? 
Tri-MipRF seems to be much faster. Does the PSNR also higher than Zip-NeRF?

**Comment by wbhu** [comment]
Thanks for your interest. We didn't compare Tri-MipRF with Zip-NeRF in our paper as they are concurrent works. From my point of view, both of the two works try to address the efficiency issue for anti-aliasing NeRF, but Zip-NeRF adopts a multi-sampling-based strategy while our method belongs to the pre-filtering-based method. For PSNR, we can only compare the results on the Blender dataset at the current point.
![image](https://github.com/wbhu/Tri-MipRF/assets/11834645/6423005e-5524-4bcf-bf0b-fe4c508f0917) 
(Tab.5 from our paper)

![image](https://github.com/wbhu/Tri-MipRF/assets/11834645/9462faf7-0400-4a77-8595-9a1aa1fc8743)
(Tab.4 from ZipNeRF paper)

**Comment by YJ-142150** [comment]
Wow! It seems Tri-MipRF is better than Zip-NeRF in Blender synthetic dataset!!
Did you tried on nerf-360 dataset, too?

**Comment by tianxiaguixin002** [comment]
Can Tri-MipRF support 360 unbounded scene ? the experiment datasets in paper are objects with mask.  thanks.

**Comment by wbhu** [comment]
Currently， it cannot support unbounded 360 scenes
