### ISSUE TITLE
About model size

### ISSUE THREAD

**Issue by cskkxjk** [wbhu/Tri-MipRF#20]
Hi~ I find the reported model size of Tri-MipRF in Table 2 is about 48.2M. 
However, i retrained Tri-MipRF as suggested and get checkpoints of 59M. 
Can you help me to figure out what causes this different and how can i get the same model size as reported?

**Comment by wbhu** [comment]
file size of the checkpoint file DOES NOT mean the model size

**Comment by cskkxjk** [comment]
> file size of the checkpoint file DOES NOT mean the model size

Thank you, the baseline TensoRF reports the checkpoint file size as their model size causes this confusion.
Now I understand that you only count the size of model.field!
