### ISSUE TITLE
why level is negative？

### ISSUE THREAD

**Issue by Lingyun0109** [wbhu/Tri-MipRF#21]
![image](https://github.com/wbhu/Tri-MipRF/assets/93696768/141c74d2-7ff3-4eb7-b7ce-0c3acc67bcef)
![image](https://github.com/wbhu/Tri-MipRF/assets/93696768/4e81dcca-1574-40ef-b22a-e271aff8c317)
请问负的level对nvdiffrast.torch.texture函数来说是什么意义呢？

**Comment by wbhu** [comment]
Please refer to #18
