### ISSUE TITLE
关于使用自定义数据导致CPU内存不足和效果不好的情况

### ISSUE THREAD

**Issue by Flyingdog-Huang** [wbhu/Tri-MipRF#25]
数据分辨率：1924*1080
数量：650张
类型：jpg（三通道）

问题一：使用数据转换脚本：convert_blender_data.py时，CPU-mem需要达到42GB
临时方案：减少数量，缩小分辨率

问题二：效果不佳（PSNR<16, loss>0.004）
详细描述：
在1920*1072-163数据中
![image](https://github.com/wbhu/Tri-MipRF/assets/43697342/e9c461f0-a5d6-4f4c-a5e8-f14138fb957e)
在800*800-325数据中
![image](https://github.com/wbhu/Tri-MipRF/assets/43697342/5dabbde8-a410-4b0c-aadd-a574159a1387)

**Comment by wbhu** [comment]
closed as duplicated issue
