### ISSUE TITLE
How to understand "To sample the cone, we cannot follow MipNeRF [3] to use the multivariate Gaussian, since the multivariate Gaussian is anisotropic but the pre-filtering in our Tri-Mip encoding is isotropic."

### ISSUE THREAD

**Issue by Terry10086** [wbhu/Tri-MipRF#34]
Thanks for your impressive work. 
I am confused about the sentence mentioned in your paper "To sample the cone, we cannot follow MipNeRF [3] to use the multivariate Gaussian, since the multivariate Gaussian is anisotropic but the pre-filtering in our Tri-Mip encoding is isotropic." I mean why does Tri-Mip need an isotropic characteristic? What is isotropic? Does it mean the same color is observed from different views?

Could you please give more explanation?

**Comment by wbhu** [comment]
'isotropic' means that the mipmap is pre-filtered with a square kernel, which cannot support sample anisotropic areas
