### ISSUE TITLE
Question for the radiuses r

### ISSUE THREAD

**Issue by SYSUykLin** [wbhu/Tri-MipRF#4]
`    @staticmethod
    def compute_ball_radii(distance, radiis, cos):
        inverse_cos = 1.0 / cos
        tmp = (inverse_cos * inverse_cos - 1).sqrt() - radiis
        sample_ball_radii = distance * radiis * cos / (tmp * tmp + 1.0).sqrt()
        return sample_ball_radii`

What is the meaning of the cos? Sound like the calculation is different from the paper. Thanks

**Comment by wbhu** [comment]
The cos means the cosine value of the angle between the ray and the principal axis of the camera. Please refer to https://github.com/wbhu/Tri-MipRF/blob/main/dataset/utils/cameras.py#L86

**Comment by MrMois** [comment]
Hello, I got another question regarding the ball radius. 

In camera.py the ray directions are normalized, hence t values (and distances) are in euclidean space. But the radii are computed on the image plane w.r.t. the unnormalized distances. Shouldn't the radii also be scaled by (1 / directions.norm) before the directions are normalized so you get the radii on the unit sphere?

Greets!
