### ISSUE TITLE
How to visualize the result?

### ISSUE THREAD

**Issue by SimonXie2004** [wbhu/Tri-MipRF#7]
I have the model.ckpt now using nerf systhetic multiscale data to train, and I want to visualize it like the video provided in the video.

**Comment by sranqiu** [comment]
In the paper, it was mentioned that the mesh was obtained using the marching cube, but I don't think it appears to be in the code.

**Comment by wbhu** [comment]
Hi, now the rgb/depth renderings are saved after the evaluation, please check it
